version: "3"

services:
  rabbitmq:
    container_name: decoupling-message-brokers-rabbitmq
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - 15672:15672
      - 5672:5672