name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:20
    services:
        rabbitmq:
          image: rabbitmq:3-management
          ports:
            - 5672:5672
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      env: 
        TEST_MESSAGEBROKER__TRANSPORT: RabbitMq
        TEST_MESSAGEBROKER__CONNECTIONSTRING: amqp://guest:guest@rabbitmq:5672/
